#
# DHT22, DHT11
# [ESPHome - DHT Temperature+Humidity](https://esphome.io/components/sensor/dht)
# ------------
#
# The DHT22 and DHT11 require external pull up resistors on the data line.
# To do this, solder a resistor with about 4.7kΩ (anything in the range
# from 1kΩ to 10kΩ probably works fine, but if you’re having issues try
# the 4.7kΩ recommended by the manufacturer) between DATA and 3.3V.
#

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
