# * PRODUCT: [ M5Stack-Atom-matrix - product details ](https://shop.m5stack.com/products/atom-matrix-esp32-development-kit)
# * PINOUT: [ M5Stack-Atom-matrix - pinout ](https://shop.m5stack.com/cdn/shop/products/7_0ba7f1df-51f7-41be-a0f6-a2bb946508c8_1200x1200.jpg)

#
# sub `lightEntity` defines the entity name of the light device in HomeAssistant to be controlled
#
substitutions:
  lightEntity: master_bathroom_main_lights
  # Library Closet Nightvision:  lifx_nightvision_6d46f2_4

esphome:
  name: m5stack-atom
  friendly_name: M5Stack-Atom
  on_boot:
    then:
      - light.turn_on:
          id: rgb_matrix
          red: 10%
          green: 10%
          blue: 10%

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret m5stack_atom_api_key

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stack-Atom Fallback Hotspot"
    password: !secret wifi_password

web_server:
  port: 80

# # Deep Sleep Feature. Needs adjustments...
# deep_sleep:
#   run_duration: 300s
#   sleep_duration: 30min

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO27
    num_leds: 25
    id: rgb_matrix
    internal: true


binary_sensor:
  #G39=Button
  - platform: gpio
    name: Button
    id: button_input_0
    internal: True
    pin:
      number: GPIO39
      inverted: true
    on_press:
      then:
        - logger.log: Button G39 Pressed
        - homeassistant.action:
            action: script.button_light_toggle
            data:
              light_name: '$lightEntity'
            #   red: '255'
            #   green: '199'
            #   blue: '71'

switch:
  - platform: homeassistant
    id: ha_light_entity
    entity_id: light.$lightEntity
    internal: true
    on_turn_on:
      - logger.log: "HA Light Turned On!"
      - light.turn_on:
          id: rgb_matrix
          brightness: 50%
          red: 0%
          green: 100%
          blue: 0%
    on_turn_off:
      - logger.log: "HA Light Turned Off!"
      - light.turn_on:
          id: rgb_matrix
          brightness: 50%
          red: 50%
          green: 0%
          blue: 50%


