esphome:
  name: plant-3
  friendly_name: plant-3

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret plant3_api_key

ota:
  - platform: esphome
    password: !secret esphome_ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: true
  ap:
    ssid: "Plant-3 Fallback Hotspot"
    password: !secret wifi_password

web_server:
  port: 80

# Deep Sleep Feature. Needs adjustments...
deep_sleep:
  run_duration: 140s
  sleep_duration: 30min

light:
  - platform: binary
    name: "Blue Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    pin: GPIO2
    id: light_output
    inverted: true

sensor:
  - platform: adc
    pin:
      number: A0
      allow_other_uses: true
    id: "adcMoisture"
    accuracy_decimals: 5
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
        - 0.38672 -> 100.0
        - 0.77441 -> 0
    name: "Plant - Moisture Level"
    update_interval: 30s
  - platform: adc
    pin:
      number: A0
      allow_other_uses: true
    id: "adcRaw_Sensor_Data"
    accuracy_decimals: 5
    name: "Plant - Sensor Voltage"
    update_interval: 30s
  - platform: wifi_signal
    name: "Plant - WiFi Signal Sensor"
    update_interval: 30s