esphome:
  name: plant-5
  friendly_name: plant-5

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret plant5_api_key

ota:
  - platform: esphome
    password: "3d7a201a45e0b181b1c69f2a4a41550c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plant-5 Fallback Hotspot"
    password: !secret wifi_password

# captive_portal:

web_server:
  port: 80

# light:
#   - platform: binary
#     name: "Blue Light"
#     output: light_output
#     id: led_light
#     restore_mode: ALWAYS_OFF

# output:
#   - platform: gpio
#     pin: GPIO2
#     id: light_output
#     inverted: true

sensor:
  # - platform: adc
  #   pin: GPIO32
  #   id: "adcMoisture"
  #   accuracy_decimals: 5
  #   unit_of_measurement: '%'
  #   filters:
  #     - calibrate_linear:
  #       - 0.39551 -> 100.0
  #       - 1.02600 -> 0
  #   name: "Plant - Moisture Level"
  #   update_interval: 30s
  - platform: adc
    pin: GPIO32
    id: "adcRaw_Sensor_Data"
    accuracy_decimals: 5
    name: "Plant - Sensor Voltage"
    update_interval: 30s
  - platform: wifi_signal
    name: "Plant - WiFi Signal Sensor"
    update_interval: 30s    